openapi: 3.0.0
info:
  description: Azion Edge Function API
  title: Edge Function
  version: "3.0"
servers:
- url: https://api.azionapi.net
- url: https://stage-api.azionapi.net
tags:
- name: edge_functions
paths:
  /edge_functions:
    get:
      parameters:
        - in: query
          name: page
          required: false
          schema:
            format: int64
            type: integer
        - in: query
          name: page_size
          required: false
          schema:
            format: int64
            type: integer
        - in: query
          name: sort
          required: false
          schema:
            type: string
        - in: query
          name: order_by
          required: false
          schema:
            type: string
      responses:
        "200":
          content:
            application/json; version=3:
              example:
                count: 1
                total_pages: 1
                schema_version: 3
                links:
                  previous: null
                  next: null
                results:
                - id: 4184
                  name: Teste
                  language: javascript
                  code: "async function handleRequest(request) {\r\n     return new\
                    \ Response(\"Hello World!\",\r\n       {\r\n           status:200\r\
                    \n       })\r\n    }\r\n    addEventListener(\"fetch\", event\
                    \ => {\r\n     event.respondWith(handleRequest(event.request))\r\
                    \n    })"
                  json_args: {}
                  function_to_run: ""
                  initiator_type: edge_application
                  active: true
                  last_editor: teste@gmail.com
                  modified: 2021-12-27T19:44:04.427738Z
                  reference_count: 0
              schema:
                $ref: '#/components/schemas/ListEdgeFunctionResponse'
          description: Success
        default:
          content:
            application/json:
              example:
                detail: Sorry unable to perform operation.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Unexpected error
      security:
      - JWT: []
      summary: edge_functions
      tags:
        - edge_functions
    post:
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/CreateEdgeFunctionRequest'
        content:
          application/json:
            example:
              name: Teste2
              language: javascript
              code: "async function handleRequest(request) {\r\n     return new Response(\"\
                Hello World!\",\r\n       {\r\n           status:200\r\n       })\r\
                \n    }\r\n    addEventListener(\"fetch\", event => {\r\n     event.respondWith(handleRequest(event.request))\r\
                \n    })"
              json_args: {}
              active: true
            schema:
              properties:
                name:
                  type: string
                language:
                  type: string
                code:
                  type: string
                json_args:
                  properties: {}
                  type: object
                active:
                  type: boolean
              type: object
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EdgeFunctionResponse"
          description: Success
        "400":
          content:
            application/json:
              example:
                name:
                - This field may not be blank
                active:
                - This field is required.
                code:
                - This field is required.
                language:
                - This field is required.
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Invalid request
        default:
          content:
            application/json:
              example:
                message: Sorry unable to perform operation.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Unexpected error
      security:
      - JWT: []
      summary: edge_functions
      tags:
      - edge_functions
  /edge_functions/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
        style: simple
      responses:
        "204":
          description: Success
        default:
          content:
            application/json:
              example:
                message: Sorry unable to perform operation.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Unexpected error
      security:
      - JWT: []
      summary: edge_functions
      tags:
      - edge_functions
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
        style: simple
      responses:
        "200":
          description: Success
          content:
            application/json:
              example:
                results:
                  id: 4184
                  name: Teste
                  language: javascript
                  code: "async function handleRequest(request) {\r\n     return new\
                    \ Response(\"Hello World!\",\r\n       {\r\n           status:200\r\
                    \n       })\r\n    }\r\n    addEventListener(\"fetch\", event\
                    \ => {\r\n     event.respondWith(handleRequest(event.request))\r\
                    \n    })"
                  json_args: {}
                  function_to_run: ""
                  initiator_type: edge_application
                  active: true
                  last_editor: lehdermann@gmail.com
                  modified: 2021-12-27T20:49:25.373356Z
                  reference_count: 0
                schema_version: 3
              schema:
                $ref: '#/components/schemas/EdgeFunctionResponse'
        default:
          content:
            application/json:
              example:
                message: Sorry unable to perform operation.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Unexpected error
      security:
      - JWT: []
      summary: edge_functions
      tags:
      - edge_functions
    patch:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/PatchEdgeFunctionRequest'
        content:
          application/json; version=3:
            example:
              name: Teste
              code: "async function handleRequest(request) {\r\n     return new Response(\"\
                Hello World!\",\r\n       {\r\n           status:200\r\n       })\r\
                \n    }\r\n    addEventListener(\"fetch\", event => {\r\n     event.respondWith(handleRequest(event.request))\r\
                \n    })"
              json_args: {}
              active: true
            schema:
              properties:
                name:
                  type: string
                code:
                  type: string
                json_args:
                  properties: {}
                  type: object
                active:
                  type: boolean
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                results:
                  id: 4184
                  name: Teste
                  language: javascript
                  code: "async function handleRequest(request) {\r\n     return new\
                    \ Response(\"Hello World!\",\r\n       {\r\n           status:200\r\
                    \n       })\r\n    }\r\n    addEventListener(\"fetch\", event\
                    \ => {\r\n     event.respondWith(handleRequest(event.request))\r\
                    \n    })"
                  json_args: {}
                  function_to_run: ""
                  initiator_type: edge_application
                  active: true
                  last_editor: lehdermann@gmail.com
                  modified: 2021-12-27T20:49:25.373356Z
                  reference_count: 0
                schema_version: 3
              schema:
                $ref: '#/components/schemas/EdgeFunctionResponse'
          description: Success
        "400":
          content:
            application/json:
              example:
                name:
                - This field may not be blank
                active:
                - This field is required.
                code:
                - This field is required.
                language:
                - This field is required.
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Invalid request
        default:
          content:
            application/json:
              example:
                message: Sorry unable to perform operation.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Unexpected error
      security:
      - JWT: []
      summary: edge_functions
      tags:
      - edge_functions
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/PutEdgeFunctionRequest'
        content:
          application/json; version=3:
            example:
              name: Teste
              code: "async function handleRequest(request) {\r\n     return new Response(\"\
                Hello World!\",\r\n       {\r\n           status:200\r\n       })\r\
                \n    }\r\n    addEventListener(\"fetch\", event => {\r\n     event.respondWith(handleRequest(event.request))\r\
                \n    })"
              json_args: {}
              active: true
            schema:
              properties:
                name:
                  type: string
                code:
                  type: string
                json_args:
                  properties: {}
                  type: object
                active:
                  type: boolean
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                results:
                  id: 4184
                  name: Teste
                  language: javascript
                  code: "async function handleRequest(request) {\r\n     return new\
                    \ Response(\"Hello World!\",\r\n       {\r\n           status:200\r\
                    \n       })\r\n    }\r\n    addEventListener(\"fetch\", event\
                    \ => {\r\n     event.respondWith(handleRequest(event.request))\r\
                    \n    })"
                  json_args: {}
                  function_to_run: ""
                  initiator_type: edge_application
                  active: true
                  last_editor: lehdermann@gmail.com
                  modified: 2021-12-27T20:49:25.373356Z
                  reference_count: 0
                schema_version: 3
              schema:
                $ref: '#/components/schemas/EdgeFunctionResponse'
          description: Success
        "400":
          content:
            application/json:
              example:
                name:
                - This field may not be blank
                active:
                - This field is required.
                code:
                - This field is required.
                language:
                - This field is required.
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
          description: Invalid request
        default:
          content:
            application/json:
              example:
                message: Sorry unable to perform operation.
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Unexpected error
      security:
      - JWT: []
      summary: edge_functions
      tags:
      - edge_functions
components:
  requestBodies:
    PutEdgeFunctionRequest:
      content:
        application/json; version=3:
          schema:
            $ref: '#/components/schemas/PutEdgeFunctionRequest'
      required: true
    PatchEdgeFunctionRequest:
      content:
        application/json; version=3:
          schema:
            $ref: '#/components/schemas/PatchEdgeFunctionRequest'
      required: true
    CreateEdgeFunctionRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateEdgeFunctionRequest'
      required: true
  schemas:
    ErrorModel:
      properties:
        code:
          type: string
      type: object
    ErrorResponse:
      properties:
        detail:
          type: string
      type: object
    Links:
      example:
        next: next
        previous: previous
      properties:
        previous:
          type: string
        next:
          type: string
      type: object
    Results:
      example:
        code: "function foo() { console.log('hello world');"
        last_editor: user@azion.com
        name: MyFunction
        active: true
        modified: modified
        language: javascript
        json_args: '{"a": 1, "b": 2}'
        id: 5
        function_to_run: function_to_run
        reference_count: 5
        initiator_type: edge_application
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        language:
          type: string
        code:
          type: string
        json_args:
          properties: {}
          type: object
        function_to_run:
          type: string
        initiator_type:
          type: string
        active:
          type: boolean
        last_editor:
          type: string
        modified:
          type: string
        reference_count:
          type: integer
          format: int64
      type: object
    ListEdgeFunctionResponse:
      example:
        schema_version: 1
        count: 1
        links:
          next: next
          previous: previous
        total_pages: 6
        results:
        - code: code
          last_editor: last_editor
          name: name
          active: true
          modified: modified
          language: language
          json_args: '{}'
          id: 5
          function_to_run: function_to_run
          reference_count: 5
          initiator_type: initiator_type
        - code: code
          last_editor: last_editor
          name: name
          active: true
          modified: modified
          language: language
          json_args: '{}'
          id: 5
          function_to_run: function_to_run
          reference_count: 5
          initiator_type: initiator_type
      properties:
        count:
          type: integer
          format: int64
        total_pages:
          type: integer
          format: int64
        schema_version:
          type: integer
          format: int64
        links:
          $ref: '#/components/schemas/Links'
        results:
          items:
            $ref: '#/components/schemas/Results'
          type: array
      type: object
    CreateEdgeFunctionRequest:
      properties:
        name:
          type: string
        language:
          type: string
        code:
          type: string
        json_args:
          properties: {}
          type: object
        active:
          type: boolean
        initiator_type:
          type: string
      type: object
    BadRequestResponse:
      properties:
        name:
          items:
            type: string
          type: array
        active:
          items:
            type: string
          type: array
        code:
          items:
            type: string
          type: array
        language:
          items:
            type: string
          type: array
      type: object
    EdgeFunctionResponse:
      example:
        schema_version: 1
        results:
          code: code
          last_editor: last_editor
          name: name
          active: true
          modified: modified
          language: language
          json_args: '{}'
          id: 5
          function_to_run: function_to_run
          reference_count: 5
          initiator_type: initiator_type
      properties:
        results:
          $ref: '#/components/schemas/Results'
        schema_version:
          type: number
      type: object
    PutEdgeFunctionRequest:
      properties:
        name:
          type: string
        code:
          type: string
        json_args:
          properties: {}
          type: object
        active:
          type: boolean
        initiator_type:
          type: string
        language:
          type: string
      type: object
    PatchEdgeFunctionRequest:
      properties:
        name:
          type: string
        code:
          type: string
        json_args:
          properties: {}
          type: object
        active:
          type: boolean
      type: object
  securitySchemes:
    JWT:
      description: |
        You must inform a token to auth.
        Usage format: `Token <TOKEN>`
      in: header
      name: Authorization
      type: apiKey

