openapi: 3.0.0
info:
  title: Edge Functions Instances API
  version: 2.0.0
  license:
    name: MIT
    url: https://github.com/aziontech/azionapi-openapi/blob/main/LICENSE.md
servers:
- description: Production
  url: https://api.azionapi.net
security:
- tokenAuth: []
paths:
  /edge_firewall/{edge_firewall_id}/functions_instances:
    get:
      summary: List all user Edge Functions Instances
      parameters:
      - explode: false
        in: path
        name: edge_firewall_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: page_size
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: sort
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: order_by
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A list of Edge Functions Instances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEdgeFunctionsInstancesResponse'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
    post:
      parameters:
      - explode: false
        in: path
        name: edge_firewall_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      summary: Create an Edge Functions Instance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEdgeFunctionsInstancesRequest'
        required: true
      responses:
        "201":
          description: Edge Functions Instance created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdgeFunctionsInstanceResponse'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /edge_firewall/{edge_firewall_id}/functions_instances/{edge_function_instance_id}:
    get:
      summary: Retrieve an Edge Functions Instance set by uuid
      parameters:
      - explode: false
        in: path
        name: edge_firewall_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - name: edge_function_instance_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          format: int64
          type: integer
      responses:
        "200":
          description: An Edge Functions Instance object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdgeFunctionsInstanceResponse'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
    put:
      summary: Overwrite some Edge Functions Instance attributes
      parameters:
      - explode: false
        in: path
        name: edge_firewall_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - name: edge_function_instance_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEdgeFunctionsInstanceRequest'
        required: true
      responses:
        "200":
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdgeFunctionsInstanceResponse'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    delete:
      summary: Delete an Edge Functions Instance by uuid
      parameters:
      - explode: false
        in: path
        name: edge_firewall_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - name: edge_function_instance_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          format: int64
          type: integer
      responses:
        "204":
          description: Successfully deleted
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
    patch:
      summary: Update some Edge Functions Instance attributes
      parameters:
      - explode: false
        in: path
        name: edge_firewall_id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - name: edge_function_instance_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEdgeFunctionsInstanceRequest'
        required: true
      responses:
        "200":
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdgeFunctionsInstanceResponse'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
components:
  schemas:
    Links:
      type: object
      properties:
        previous:
          type: string
        next:
          type: string
      example:
        next: next
        previous: previous
    EdgeFunctionsInstance:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        last_editor:
          type: string
        last_modified:
          type: string
        json_args: {}
        edge_function:
          type: integer
          format: int64
      example:
        edge_function: 3254
        name: "New Edge Function Instance"
        json_args: {}
        id: 1614
    ListEdgeFunctionsInstancesResponse:
      type: object
      properties:
        count:
          type: integer
          format: int64
        total_pages:
          type: integer
          format: int64
        schema_version:
          type: integer
          format: int64
        links:
          $ref: '#/components/schemas/Links'
        results:
          type: array
          items:
            $ref: '#/components/schemas/EdgeFunctionsInstance'
      example:
        schema_version: 1
        count: 0
        links:
          next: next
          previous: previous
        total_pages: 6
        results:
        - edge_function: 3254
          name: "New Edge Function Instance"
          json_args: {}
          id: 1614
        - edge_function: 3254
          name: "New Edge Function Instance"
          json_args: {}
          id: 1614
    CreateEdgeFunctionsInstancesRequest:
      type: object
      properties:
        name:
          type: string
          example: Edge Functions Instance
        edge_function:
          type: integer
          format: int64
        json_args: {}
    EdgeFunctionsInstanceResponse:
      type: object
      properties:
        results:
          $ref: '#/components/schemas/EdgeFunctionsInstance'
        schema_version:
          type: number
      example:
        schema_version: 0.80082819046101150206595775671303272247314453125
        results:
          edge_function: 3254
          name: "New Edge Function Instance"
          json_args: {}
          id: 1614
    UpdateEdgeFunctionsInstanceRequest:
      $ref: '#/components/schemas/CreateEdgeFunctionsInstancesRequest'
  securitySchemes:
    tokenAuth:
      type: apiKey
      name: Authorization
      in: header
      description: |
        You must inform a token to auth.
        Usage format: `Token <TOKEN>`
